### ISSUE TITLE
Compatibility issue with strapi 4.11.5

### ISSUE THREAD

**Issue by abidfs** [ComfortablyCoding/strapi-plugin-website-builder#38]
I have this configuration in `./config/plugins.ts`
```typescript
export default ({ env }) => ({
  "website-builder": {
    enabled: true,
    config: {
      url: "https://localhost:3000",
      trigger: {
        type: "manual",
      },
    },
  },
});
```

When I try to start the strapi using `yarn develop` I am seeing this error
```
/projects/strapi-cms/node_modules/yup/lib/util/createValidation.js:54
      const error = new _ValidationError.default(_ValidationError.default.formatError(overrides.message || message, nextParams), value, nextParams.path, overrides.type || name);
                    ^

ValidationError: url is invalid
    at createError (/projects/strapi-cms/node_modules/yup/lib/util/createValidation.js:54:21)
    at /projects/strapi-cms/node_modules/yup/lib/util/createValidation.js:72:107 {
  value: { trigger: { type: undefined, events: undefined, cron: undefined } },
  path: 'url',
  type: undefined,
  errors: [ 'url is invalid' ],
  params: {
    value: undefined,
    originalValue: undefined,
    label: undefined,
    path: 'url'
  },
  inner: []
}

Node.js v18.16.0
```

I've added some logs in the plugin's `/server/config/index.js` file and looks like it's not able to pick the config correctly, the config object is empty `{ }`

**Comment by ComfortablyCoding** [comment]
Strange, i woud assume its a strapi ts issue or some configuration issue. Do you by ay chance have a sample repo that i can look at that reproduces this issue? Or it happens on clean ts install as well?

**Comment by abidfs** [comment]
It happens on clean install as well.
Here are the steps

1. Create a brand new strapi project
2. Add this plugin dependency
3. Add the above configuration in `./config/plugins.ts`

**Comment by ComfortablyCoding** [comment]
Thanks, I will see if I can find the cause.

**Comment by ComfortablyCoding** [comment]
I have done the following steps and cannot replicate this issue

1. Create a brand new strapi project via `npx create-strapi-app@latest --ts --quickstart strapi-latest-ts`
2. Add this plugin dependency via `npm i strapi-plugin-website-builder`
3. Create configuration file at `./config/plugins.ts`
4. Add the following config
```js
export default ({ env }) => ({
  "website-builder": {
    enabled: true,
    config: {
      url: "https://localhost:3000",
      trigger: {
        type: "manual",
      },
    },
  },
});
```

I tried it with 4.11.5
```json
  "dependencies": {
    "@strapi/plugin-i18n": "4.11.5",
    "@strapi/plugin-users-permissions": "4.11.5",
    "@strapi/strapi": "4.11.5",
    "better-sqlite3": "8.0.1",
    "strapi-plugin-website-builder": "^2.2.2"
  },
```
and the latest (4.11.7)
```json
  "dependencies": {
    "@strapi/plugin-i18n": "4.11.7",
    "@strapi/plugin-users-permissions": "4.11.7",
    "@strapi/strapi": "4.11.7",
    "better-sqlite3": "8.0.1",
    "strapi-plugin-website-builder": "^2.2.2"
  },
```
Node version
```txt
node v16.18.0 (npm v8.19.2)
```
Plugin Version
```txt
v2.2.2
```

The only reasons I can think of that would cause this issue for you are
1. The plugin config is not actually at `.config/plugins.ts`
2. The plugin version is 2.2.0 or lower and are experiencing the issue outlined in https://github.com/ComfortablyCoding/strapi-plugin-website-builder/issues/19

**Comment by ComfortablyCoding** [comment]
Closing due to inactivity. Will reopen if reproducible steps are provided.
